# Generated by Django 6.0.5 on 2026-05-27 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invitation_expires_at_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 3, 15, 14, 54, 73170, tzinfo=datetime.timezone.utc)),
        ),
    ]
